"""Fix Game-Challenge foreign key

Revision ID: 34c50a367032
Revises: cd3e08b41381
Create Date: 2025-03-03 20:26:02.946566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c50a367032'
down_revision = 'cd3e08b41381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id_fk', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_challenge_game",  # Explicitly name the constraint
            "game",  # Referencing table
            ["game_id_fk"],  # Column in "challenge"
            ["id"]  # Column in "game"
        )
    # ### end Alembic commands ###



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_constraint("fk_challenge_game", type_="foreignkey")  # Ensure this matches the constraint name
        batch_op.drop_column("game_id_fk")
    # ### end Alembic commands ###

